#[derive(Copy, Clone, PartialEq)]
pub struct VRegister(pub(crate) usize);
pub enum Opcode {
    NoOp,
    ScD(u8),
    ClS,
    Ret,
    ScR,
    ScL,
    Exit,
    LoRes,
    HiRes,
    Jp(u16),
    JpReg(u16),
    Call(u16),
    SEByte(VRegister, u8),
    SEReg(VRegister, VRegister),
    SNEByte(VRegister, u8),
    SNEReg(VRegister, VRegister),
    LdByte(VRegister, u8),
    LdReg(VRegister, VRegister),
    LdToI(u16),
    LDkey(VRegister),
    LdSpr(VRegister),
    LdDeci(VRegister),
    LdVxToI(VRegister),
    LdIToVx(VRegister),
    LdVxToDT(VRegister),
    LdDTToVx(VRegister),
    LdVxToST(VRegister),
    AddByte(VRegister, u8),
    AddReg(VRegister, VRegister),
    AddToI(VRegister),
    Or(VRegister, VRegister),
    And(VRegister, VRegister),
    Xor(VRegister, VRegister),
    Sub(VRegister, VRegister),
    ShR(VRegister, VRegister),
    SubN(VRegister, VRegister),
    ShL(VRegister, VRegister),
    Rand(VRegister, u8),
    Drw(VRegister, VRegister, u8),
    SkP(VRegister),
    SkNP(VRegister),
}

pub const fn nibble_op_code(opcode: u16) -> (u8, u8, u8, u8) {
    (
        ((opcode & 0xf000) >> 12) as u8,
        ((opcode & 0x0f00) >> 8) as u8,
        ((opcode & 0x00f0) >> 4) as u8,
        (opcode & 0x000f) as u8,
    )
}
pub fn decode_opcode(opcode: u16) -> Opcode {
    use Opcode::*;
    let nibbles = nibble_op_code(opcode);
    let n = nibbles.3;
    let kk = opcode as u8;
    let nnn = opcode & 0xfff;
    let (x_reg, y_reg) = (VRegister(nibbles.1 as usize), VRegister(nibbles.2 as usize));
    match nibbles {
        (0, 0, 0, 0) => NoOp,
        (0, 0, 0xC, _) => ScD(n),
        (0, 0, 0xE, 0) => ClS,
        (0, 0, 0xE, 0xE) => Ret,
        (0, 0, 0xF, 0xB) => ScR,
        (0, 0, 0xF, 0xC) => ScL,
        (0, 0, 0xF, 0xD) => Exit,
        (0, 0, 0xF, 0xE) => LoRes,
        (0, 0, 0xF, 0xF) => HiRes,
        (0x1, _, _, _) => Jp(nnn),
        (0x2, _, _, _) => Call(nnn),
        (0x3, _, _, _) => SEByte(x_reg, kk),
        (0x4, _, _, _) => SNEByte(x_reg, kk),
        (0x5, _, _, _) => SEReg(x_reg, y_reg),
        (0x6, _, _, _) => LdByte(x_reg, kk),
        (0x7, _, _, _) => AddByte(x_reg, kk),
        (0x8, _, _, 0x0) => LdReg(x_reg, y_reg),
        (0x8, _, _, 0x1) => Or(x_reg, y_reg),
        (0x8, _, _, 0x2) => And(x_reg, y_reg),
        (0x8, _, _, 0x3) => Xor(x_reg, y_reg),
        (0x8, _, _, 0x4) => AddReg(x_reg, y_reg),
        (0x8, _, _, 0x5) => Sub(x_reg, y_reg),
        (0x8, _, _, 0x6) => ShR(x_reg, y_reg),
        (0x8, _, _, 0x7) => SubN(x_reg, y_reg),
        (0x8, _, _, 0xE) => ShL(x_reg, y_reg),
        (0x9, _, _, 0) => SNEReg(x_reg, y_reg),
        (0xA, _, _, _) => LdToI(nnn),
        (0xB, _, _, _) => JpReg(nnn),
        (0xC, _, _, _) => Rand(x_reg, kk),
        (0xD, _, _, _) => Drw(x_reg, y_reg, n),
        (0xE, _, 0x9, 0xE) => SkP(x_reg),
        (0xE, _, 0xA, 0x1) => SkNP(x_reg),
        (0xF, _, 0x0, 0x7) => LdDTToVx(x_reg),
        (0xF, _, 0x0, 0xA) => LDkey(x_reg),
        (0xF, _, 0x1, 0x5) => LdVxToDT(x_reg),
        (0xF, _, 0x1, 0x8) => LdVxToST(x_reg),
        (0xF, _, 0x1, 0xE) => AddToI(x_reg),
        (0xF, _, 0x2, 0x9) => LdSpr(x_reg),
        (0xF, _, 0x3, 0x3) => LdDeci(x_reg),
        (0xF, _, 0x5, 0x5) => LdVxToI(x_reg),
        (0xF, _, 0x6, 0x5) => LdIToVx(x_reg),
        (_, _, _, _) => NoOp,
    }
}