[package]
name = "chippy8"
version = "0.1.0"
edition = "2021"
license = "MIT"
rust-version = "1.56"
repository = "https://github.com/Muu79/chippy"
readme = "README.md"
keywords = ["chip8", "schip8", "super-chip",  "xo-chip", "emulator"]
categories = ["emulators", "no-std"]

[features]
default = ["std"]
std = []